# Generated by Django 5.0.14 on 2025-06-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='status',
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(upload_to='berita/images'),
        ),
    ]
